### ISSUE TITLE
Dogfooding readme definition link is a 404

### ISSUE THREAD

**Issue by wmcnamara** [oliverbooth/X10D#5]
The README mentions:
> (I'm also dogfooding this library, so there's that.)

and provides a link to a definition for "dogfooding", which unfortunately no longer exists.
Link in question: https://deviq.com/dogfooding/

**Additional context**
Not sure if they're the exact same definition, but this one by pcmag seems to be a suitable replacement 
https://www.pcmag.com/encyclopedia/term/dogfooding

**Comment by oliverbooth** [comment]
Nice find! Fixed in 8713821b8b6196fc09c4b9d6956692b90eb67759
