### ISSUE TITLE
[Request]: Delimiter splitting for Span/ReadOnlySpan

### ISSUE THREAD

**Issue by RealityProgrammer** [oliverbooth/X10D#59]
### Type to extend

System.Span<T>/System.ReadOnlySpan<T>

### Signature

```csharp
1. SpanSingleDelimiterEnumerator<T> EnumerateDelimiter<T>(ReadOnlySpan<T> delimiter) where T : IEquatable<T>

2. SpanMultipleDelimiterEnumerator<T> EnumerateDelimiters<T>(ReadOnlySpan<T> delimiters) where T : IEquatable<T>
```

### Summary

```md
1. Enumerate the span based on delimiter formed by every elements of the delimiter
2. Enumerate the span based on each delimiter element of the delimiters span
```

### Parameters

1.
| Parameter | Type    | Description                        |
| -         | -       | -                                  |
| delimiter | `ReadOnlySpan<T>` | Delimiter that formed by every element in the span |
2.
| Parameter | Type    | Description                        |
| -         | -       | -                                  |
| delimiter | `ReadOnlySpan<T>` | Span which contains every elements act as a delimiter |

### Benefits

Reduce boilerplate code to enumerate span based on delimiter. Act like `System.Text.MemoryExtensions.EnumerateLines`, but with custom delimiter(s)

### Drawbacks

1. Every elements will form the whole delimiter, thus only 1 delimiter.
2. Every elements act as a delimiter, so 2 elements delimiter is not possible

### Implementation Example

```csharp
1: 
Method:
return new SpanSingleDelimiterEnumerator<T>(span, delimiter);

Requirement Type:
public ref struct SpanSingleDelimiterEnumerator<T> where T : IEquatable<T> {
    private ReadOnlySpan<T> _span;
    private readonly ReadOnlySpan<T> _delimiter;

    public SpanSingleDelimiterEnumerator(ReadOnlySpan<T> span, ReadOnlySpan<T> delimiter) {
        _span = span;
        _delimiter = delimiter;
        Current = default;
    }

    public SpanSingleDelimiterEnumerator<T> GetEnumerator() => this;
    public ReadOnlySpan<T> Current { get; private set; }

    public bool MoveNext() {
        if (_span.Length == 0) return false;

        var index = _span.IndexOf(_delimiter);
        if (index == -1) {
            Current = _span;
            _span = default;
             return true;
        }

        Current = _span[0..index];
        _span = _span[(index + _delimiter.Length)..];
        return true;
    }
}

2.
Method:
return new SpanMultipleDelimiterEnumerator<T>(span, delimiters);

Requirement Type:
public ref struct SpanMultipleDelimiterEnumerator<T> where T : IEquatable<T> {
    private ReadOnlySpan<T> _span;
    private readonly ReadOnlySpan<T> _delimiters;

    public SpanMultipleDelimiterEnumerator(ReadOnlySpan<T> span, ReadOnlySpan<T> delimiters) {
        _span = span;
        _delimiters = delimiters;
        Current = default;
    }

    public SpanMultipleDelimiterEnumerator<T> GetEnumerator() => this;
    public ReadOnlySpan<T> Current { get; private set; }

    public bool MoveNext() {
        if (_span.Length == 0) return false;

        var index = _span.IndexOfAny(_delimiters);
        if (index == -1) {
            Current = _span;
            _span = default;
            return true;
        }

        Current = _span[0..index];
        _span = _span[(index + 1)..];
        return true;
    }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oliverbooth** [comment]
Is there any particular reason that `T` is constrained to `IEquatable<T>`?

**Comment by RealityProgrammer** [comment]
IndexOf and IndexOfAny requires it

**Comment by oliverbooth** [comment]
That makes sense. And seeing as the most common use-cases for `Span` is with `char` and `byte`, it's essentially a non-issue since primitives are inherently `IEquatable`

**Comment by oliverbooth** [comment]
I wonder if it would be smart to also have a single T delimeter, as well as Span delimeter. Essentially serving as an equivalent to `string.Split(char)`. Keeping the span delimeter too, since `string.Split(string)` is also an overload

**Comment by RealityProgrammer** [comment]
would be nice and convenient, as I usually use this for Span of char (string) so I don't really think much about other types.

So yes, you can duplicate the enumerator class and change the delimiter detection code to make it compatible to single value instead of collection.

**Comment by oliverbooth** [comment]
This has been introduced with ed8651172b3760cafca3d08e59239d9762bf583f and 53e8b2ff64c78f00550e49c02e71fd98449d61aa
