### ISSUE TITLE
[Request]: Consume method for nullable struct

### ISSUE THREAD

**Issue by RealityProgrammer** [oliverbooth/X10D#61]
### Type to extend

`System.Nullable<T>`

### Signature

```csharp
bool Consume<T>(ref T receiver) where T : struct
```

### Summary

```md
Consume the nullable value if it has one and return true, otherwise return false.
```

### Parameters

| Parameter | Type    | Description                        |
| -         | -       | -                                  |
| receiver | `T` | Receiver instance  |

### Benefits

Quick way to cut down some line when working with Nullable<T> type by compress null check and assignment in one simple method

### Drawbacks

Method calling (no idea whether the method will be inlined, even with AggressiveInlining), small ref overhead (negligible)

### Implementation Example

```csharp
if (!nullable.HasValue) return false;

receiver = nullable.Value;
return true;
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RealityProgrammer** [comment]
One more addition detail: If the `this` parameter is also marked with `ref` and assign null to it after the receiver assignment, we can have an extension method that act like `std::move`, move the value to receiver and nullify the donor

**Comment by oliverbooth** [comment]
Perhaps a name like `TryGetValue`, so it's consistent with other .NET APIs. And in such a case, this should be an `out` parameter.
