### ISSUE TITLE
Merge X10D.Performant in with this repository

### ISSUE THREAD

**Issue by oliverbooth** [oliverbooth/X10D#78]
## Summary
The aim of this is change to merge the functionality provided by the [X10D.Performant](https://github.com/Redageddon/X10D.Performant) fork into the main X10D release.

## Rationale
The author of X10D.Performant, Redageddon, has decided to obsolesce his fork in favour of this one. The package has already been delisted and marked as legacy on NuGet.org, citing X10D as the alternative to use.

## Remarks
[A branch](https://github.com/oliverbooth/X10D/tree/feature/merge_x10d.performant) has been created into which a PR can be made for this task, so that drafts and commits do not affect the workflow of main or develop until it's ready.

**Comment by Redageddon** [comment]
soon:tm:

**Comment by oliverbooth** [comment]
Closing because PR #82 was closed.
